package quest.feature.parent.presentation

import androidx.compose.runtime.staticCompositionLocalOf
import quest.feature.journey.presentation.LessonStrings
import quest.feature.school.domain.SchoolBranding

/** The app's copy in English and Arabic. The lesson and exam screens keep theirs in [LessonStrings]. */
data class Strings(
    val isRtl: Boolean,
    val grownUps: String, val enterPin: String, val createPin: String, val repeatPin: String, val pinMismatch: String, val wrongPin: String,
    val parentHome: String, val todaysLessons: String, val noLessonsToday: String, val addLesson: String, val calendar: String,
    val progress: String, val settings: String, val backToChild: String,
    val subject: String, val math: String, val english: String, val chooseSource: String, val pdf: String, val powerpoint: String,
    val camera: String, val gallery: String, val typeTask: String, val selectedFiles: String, val readSlides: String, val remove: String,
    val typedTaskTitle: String, val typedTaskHint: String, val readIt: String,
    val uploading: String, val reading: String, val generating: String, val ready: String, val readyBody: String, val somethingWrong: String,
    val tryAgain: String, val chooseAnother: String,
    val confirmTitle: String, val confirmBody: String, val unsureQuestion: String, val addSkill: String, val skillName: String,
    val makeQuest: String, val keepAtLeastOne: String, val slides: String,
    val goingWell: String, val gettingThere: String, val needsAnotherLook: String, val notPlayedYet: String, val firstTry: String,
    val lastPractised: String, val queuedFor: String, val attempts: String,
    val grade: String, val curriculum: String, val save: String,
    val practiceLength: String, val questions: String, val language: String, val changePin: String, val deleteFiles: String,
    val deleteFilesBody: String, val deleted: String, val privacy: String, val privacyBody: String, val version: String,
    val today: String, val noLessonsThatDay: String, val statusLabel: Map<String, String>,
    val weekdays: List<String>, val months: List<String>,
    val accuracyWords: Map<String, String> = emptyMap(),
    // v3
    val signIn: String = "Sign in", val register: String = "Create account", val signInBody: String = "Parents sign in; children just play.",
    val email: String = "Email", val password: String = "Password", val createAccount: String = "Create account", val googleSignIn: String = "Continue with Google",
    val haveAccount: String = "I already have an account", val noAccount: String = "New here? Create an account",
    val american: String = "American", val british: String = "British",
    val children: String = "Children", val signOut: String = "Sign out",
    val level: String = "Level", val unlockLevel: String = "Unlock", val lessonPanel: String = "Lesson panel", val objectives: String = "Learning objectives",
    val supported: String = "Supported", val challengeIdeas: String = "Challenge", val tipsPerStop: String = "Tips for each step", val played: String = "Completed", val notPlayed: String = "Not started", val playRecording: String = "Play the recording",
    val weakSkills: String = "Needs another look", val noWeakSkills: String = "Nothing to review right now — great!", val streak: String = "Day streak",

    // D16 slice 4 / teacher flow step 9: what the teacher released. Parent mode only — §6 keeps numbers off child screens.
    val teacherMarks: String = "Marked by the teacher",
    val examUndeliveredTitle: String = "Exam answers not delivered",
    val examUndeliveredBody: String = "{n} answers of “{title}” are on this device only and have not reached the school. Open the exam while online. If the exam has closed, ask the teacher to re-open it — the answers are kept and are sent then.",
    // M2 — the biometric lock. {app} is the app's name and {with} one of the three biometric names below.
    val biometricFace: String = "Face ID",
    val biometricTouch: String = "Touch ID",
    val biometricGeneric: String = "fingerprint or face",
    val lockTitle: String = "{app} is locked",
    val lockBody: String = "Unlock with {with} or your device passcode.",
    val lockBodyPasscode: String = "Unlock with your device passcode, or sign in with your password.",
    val lockReason: String = "Unlock {app}",
    val lockTryAgain: String = "Try again",
    val lockUsePassword: String = "Sign in with password",
    val biometricOfferTitle: String = "Unlock with {with}?",
    val biometricOfferBody: String = "Next time, open {app} with {with} instead of your password. You can change this in Settings.",
    val biometricOfferAccept: String = "Turn on",
    val biometricOfferDecline: String = "Not now",
    val security: String = "Security",
    val biometricSetting: String = "Unlock with {with}",
    val biometricSettingHint: String = "Asked when the app opens, after a minute away, and for the parent area.",
    val biometricOn: String = "On",
    val biometricOff: String = "Off",
    val parentAreaReason: String = "Open the parent area",
    val examResultPending: String = "This is an exam. The result, the questions and the teacher's comment appear here after the teacher releases them.",
    val teacherComment: String = "Teacher's note",
    val teacherQuestionNote: String = "Teacher note",
    val needsAttention: String = "Needs attention",
    val passed: String = "Passed",
    /** The teacher's four bands, keyed by the server's own words (`grading/Bands.java`). */
    val scoreBands: Map<String, String> = mapOf(
        "emerging" to "Emerging", "developing" to "Developing", "secure" to "Secure", "exceeding" to "Exceeding",
    ),
    // C3: Parent ↔ Teacher chat
    val messages: String = "Messages",
    val chat: String = "Chat",
    val noTeachers: String = "No teachers assigned yet",
    val childNotPlaced: String = "Your child is not placed in a class yet. Ask the teacher to place them.",
    val typeMessage: String = "Type a message…",
    val send: String = "Send",
    val online: String = "Online",
    val offline: String = "Offline",
    val connecting: String = "Connecting…",
    val isTyping: String = "is typing…",
    val emptyConversation: String = "No messages yet. Send a note to the teacher!",
    val retry: String = "Retry",
    val failedToSend: String = "Failed to send",
    val chatDisabled: String = "Chat is currently disabled by the school.",
    // Attendance
    val attendance: String = "Attendance",
    val todaysAttendance: String = "Today's Attendance",
    val present: String = "Present",
    val absent: String = "Absent",
    val late: String = "Late",
    val excused: String = "Excused",
    val noAttendanceRecorded: String = "Not recorded yet",
    val attendanceNote: String = "Note from teacher",
    // R8: the parent writes to the coordinator of a subject, and may mark that first message a complaint (DR3).
    val teacherRole: String = "Teacher",
    val coordinatorRole: String = "Subject coordinator",
    val teachersGroup: String = "Your child's teachers",
    val coordinatorsGroup: String = "Subject coordinators",
    val pickCoordinator: String = "Who would you like to write to?",
    val complaintBadge: String = "Complaint",
    val statusOpen: String = "Open",
    val statusResolved: String = "Resolved",
    val resolvedBanner: String = "Resolved — the coordinator answered this. You can still write here.",
    // M4 (D7): the banner names who the parent was talking to — a complaint the manager resolved is not the coordinator's.
    val resolvedBannerTeacher: String = "Resolved — the teacher answered this. You can still write here.",
    val resolvedBannerManager: String = "Resolved — the department manager answered this. You can still write here.",
    val resolvedBannerAdmin: String = "Resolved — the school administration answered this. You can still write here.",
    val markAsComplaint: String = "This is a complaint",
    val markAsComplaintHint: String = "The coordinator sees it as an open complaint in her complaints list.",
    /**
     * The six subjects by the server's own key (`quest.api.dto.Subject`), so a coordinator's `subject` reads in the
     * parent's language instead of as the raw wire word. A key nobody here knows is shown as the server wrote it,
     * exactly as an unknown score band is.
     */
    val subjectNames: Map<String, String> = mapOf(
        "math" to "Math", "english" to "English", "science" to "Science",
        "french" to "French", "religion" to "Religion", "arabic" to "Arabic",
    ),
    val emptyConversationCoordinator: String = "No messages yet. Write to the coordinator of this subject.",

    // RM4 (DR5): the parent also writes to the manager of her child's department — about the school, the child or a
    // coordinator — and a complaint is allowed there too.
    val managerRole: String = "Department manager",
    val managersGroup: String = "Department manager",
    val emptyConversationManager: String = "No messages yet. Write to the manager of the department.",
    val markAsComplaintHintManager: String = "The manager sees it as an open complaint in her complaints list.",

    // RM4 (DR4, DR6), split in two by MH3: the Weekly plan page and the Announcements page.
    val weeklyPlan: String = "Weekly plan",
    val announcements: String = "Announcements",
    // M4 (D5): the Notifications tab — her own rows above the school's announcements and events.
    val notificationsTitle: String = "Notifications",
    val updatesGroup: String = "Updates",
    val updateMessage: String = "Message",
    val updateResult: String = "Result released",
    val updateHomework: String = "New homework",
    val updateOther: String = "Update",
    /** M5: grouped, because this class is at the JVM's limit of constructor parameters. */
    val notices: NoticeStrings = NoticeStrings.en,
    val thisWeeksPlan: String = "This week's plan",
    val earlierPlans: String = "Earlier weeks",
    /** `{date}` is replaced with the Sunday the plan's week starts on. */
    val weekOf: String = "Week of {date}",
    val announcementsGroup: String = "Announcements",
    val eventsGroup: String = "Events",
    val noBroadcasts: String = "Nothing from the school yet.",
    val noWeeklyPlan: String = "No weekly plan yet. The department manager sends one each week.",
    /** MH3: an image that would not download. No red and no X (§7) — a sentence and a Try again button. */
    val imageFailed: String = "The plan could not be downloaded. Try again when you are back online.",
    val tapToClose: String = "Tap to close",
    val broadcastsDisabled: String = "This is not enabled for your school.",
    val newBadge: String = "New",
    val attachment: String = "Attachment",
    /** A document, which the app has no route to render: the card names it and says where it can be opened. */
    val attachmentOnDashboard: String = "Available on the dashboard",
    // MH1/MH3: her own mobile number, the one the department manager reaches her on.
    val phone: String = "Mobile number",
    val phoneHint: String = "For the school to reach you, e.g. +971501234567",
    val phoneInvalid: String = "A mobile number is 7 to 15 digits, with an optional leading +.",
    val phoneSaved: String = "Saved",
    /** Not her mistake: the number is still in the field and the button is still there. */
    val phoneSaveFailed: String = "Could not save just now. Check your connection and try again.",
    /** `{subject}` and `{curriculum}` are replaced with the words the feed named. */
    val fromCoordinator: String = "From your {subject} coordinator",
    val fromManager: String = "From the {curriculum} department manager",
    val fromAuthor: String = "From {name}",

    // MH4: the student home (`FormalStudentScreen`). §7 keeps percentages and timers off it, but the copy itself is
    // read by the same parent who set the language — an Arabic school got an English, left-to-right child screen.
    val allSubjects: String = "All Subjects",
    val student: String = "Student",
    /** `{n}` is the streak in days — a count of days, not a countdown (§7 allows the streak, not a timer). */
    val dayStreakShort: String = "{n}d streak",
    val loadingCoursework: String = "Loading your coursework…",
    val noCourseworkToday: String = "No coursework scheduled today",
    val noCourseworkForSubject: String = "No assignments found for this subject",
    val checkBackSoon: String = "Check back soon for new lessons and tasks.",
    val lessonLocked: String = "Locked",
    val lessonCompleted: String = "Completed",
    val lessonReview: String = "Review",
    val lessonAssignedToday: String = "Assigned Today",
    val lessonAvailable: String = "Available",
    val lessonUnlockHint: String = "Complete prior lessons to unlock",
    val lessonReinforce: String = "Reinforce concepts",
    val lessonStandard: String = "Standard curriculum lesson",
    val startLesson: String = "Start Lesson",
    val openLesson: String = "Open",
    val parentPortal: String = "Parent Portal",
    /** `{earned}` / `{total}` stars. A fraction, never a percentage (§7). */
    val lessonScore: String = "Score: {earned}/{total}",
    // M1: a weekly plan (or an announcement's attachment) may be a PDF, opened in the system viewer.
    val pdfDocument: String = "PDF document",
    val openDocument: String = "Open",
    val documentOpening: String = "Opening…",
    val documentFailed: String = "The file could not be opened. Check your connection, and that this device has a PDF viewer.",
    /** The product's own name, shown when neither the school nor the platform has named the app. */
    val appName: String = "MySchool",
    // M1: Light / Dark / System.
    val appearance: String = "Appearance",
    val appearanceSystem: String = "System",
    val appearanceLight: String = "Light",
    val appearanceDark: String = "Dark",
    // S1: a thread the school administration opened with the parent.
    val schoolAdministration: String = "School administration",
    val emptyConversationAdmin: String = "No messages yet.",
    // M1: New message — child, then topic, then who. A complaint may go to any of the three roles.
    val newMessage: String = "New message",
    val newMessageChild: String = "About which child?",
    val newMessageTopic: String = "What is it?",
    val topicQuestion: String = "Question",
    val topicComplaint: String = "Complaint",
    val complaintExplained: String = "A complaint is shown with a badge and a status — open, then resolved — to you and to the person you send it to.",
    val newMessageNobody: String = "Nobody to write to for this child yet.",
    val markAsComplaintHintTeacher: String = "The teacher sees it as an open complaint.",
    // M1: the admin links children to the parent's account; the app only lists them.
    val chooseStudent: String = "Choose a student to open their home page.",
    val currentChild: String = "Current",
    val noChildrenLinked: String = "Your school has not linked a child to this account yet — contact the school.",
    val checkAgain: String = "Check again",
    /** The lesson and exam screens' own table; the student home draws its exam badge and read-aloud label from it. */
    val lesson: LessonStrings = LessonStrings.en,
) {
    fun accuracy(words: String) = accuracyWords[words] ?: words

    /** An unknown band is shown as the server wrote it rather than hidden, exactly as an unknown error code is. */
    fun scoreBand(key: String) = scoreBands[key.lowercase()] ?: key

    companion object {
        val en = Strings(
            isRtl = false,
            grownUps = "Parent access", enterPin = "Enter your PIN", createPin = "Create a 4-digit PIN", repeatPin = "Repeat the PIN",
            pinMismatch = "The PINs did not match. Try again.", wrongPin = "That is not the PIN.",
            parentHome = "Parent mode", todaysLessons = "Today's lessons", noLessonsToday = "No lesson added today yet.",
            addLesson = "Add lesson", calendar = "Calendar", progress = "Progress", settings = "Settings", backToChild = "Back to child mode",
            subject = "Subject", math = "Math", english = "English", chooseSource = "Add today's slides", pdf = "PDF", powerpoint = "PowerPoint",
            camera = "Camera", gallery = "Photos", typeTask = "Type a task", selectedFiles = "Selected", readSlides = "Read the slides", remove = "Remove",
            typedTaskTitle = "Type the task", typedTaskHint = "For example: Count by 2s to 20 using the number line", readIt = "Read it",
            uploading = "Uploading…", reading = "Reading the slides…", generating = "Making the questions…", ready = "The quest is ready!",
            readyBody = "Your child can play it from the map now. The uploaded files have been deleted.",
            somethingWrong = "Something went wrong", tryAgain = "Try again", chooseAnother = "Choose another file",
            confirmTitle = "What was taught?", confirmBody = "Untick anything that is not a skill from today.",
            unsureQuestion = "Not sure — which one?", addSkill = "Add a skill", skillName = "Skill name", makeQuest = "Make the quest",
            keepAtLeastOne = "Keep at least one skill.", slides = "slides",
            goingWell = "Going well", gettingThere = "Getting there", needsAnotherLook = "Needs another look", notPlayedYet = "Not started yet",
            firstTry = "Right on the first try", lastPractised = "Last practised", queuedFor = "Coming back on", attempts = "answers",
            grade = "Grade", curriculum = "Curriculum", save = "Save",
            practiceLength = "Practice length", questions = "questions", language = "Language", changePin = "Change PIN",
            deleteFiles = "Delete uploaded files", deleteFilesBody = "Removes every uploaded slide file from the server. Skills and questions stay.",
            deleted = "Files deleted", privacy = "Privacy", privacyBody = "Slides are read once and deleted. Only skills and questions are kept, on this device.",
            version = "Version", today = "Today", noLessonsThatDay = "No lesson on this day.",
            statusLabel = mapOf("uploading" to "Uploading", "reading" to "Reading", "needs_confirmation" to "Needs your OK", "generating" to "Making questions", "ready" to "Ready", "error" to "Problem"),
            weekdays = listOf("Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"),
            months = listOf("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"),
        )

        val ar = Strings(
            isRtl = true,
            grownUps = "دخول وليّ الأمر", enterPin = "أدخل الرقم السري", createPin = "أنشئ رقمًا سريًا من 4 أرقام", repeatPin = "أعد إدخال الرقم السري",
            pinMismatch = "الرقمان غير متطابقين. حاول مجددًا.", wrongPin = "الرقم السري غير صحيح.",
            parentHome = "وضع الأهل", todaysLessons = "دروس اليوم", noLessonsToday = "لم يُضف درس اليوم بعد.",
            addLesson = "إضافة درس", calendar = "التقويم", progress = "التقدّم", settings = "الإعدادات", backToChild = "العودة إلى وضع الطفل",
            subject = "المادة", math = "رياضيات", english = "إنجليزي", chooseSource = "أضف شرائح اليوم", pdf = "PDF", powerpoint = "PowerPoint",
            camera = "الكاميرا", gallery = "الصور", typeTask = "اكتب المهمة", selectedFiles = "المحدد", readSlides = "اقرأ الشرائح", remove = "إزالة",
            typedTaskTitle = "اكتب المهمة", typedTaskHint = "مثال: العدّ بالاثنينات حتى 20 على خط الأعداد", readIt = "اقرأها",
            uploading = "جارٍ الرفع…", reading = "جارٍ قراءة الشرائح…", generating = "جارٍ إعداد الأسئلة…", ready = "المهمة جاهزة!",
            readyBody = "يمكن لطفلك اللعب الآن من الخريطة. تم حذف الملفات المرفوعة.",
            somethingWrong = "حدث خطأ ما", tryAgain = "حاول مجددًا", chooseAnother = "اختر ملفًا آخر",
            confirmTitle = "ماذا تعلّم اليوم؟", confirmBody = "ألغِ تحديد أي شيء ليس مهارة من درس اليوم.",
            unsureQuestion = "غير متأكد — أيهما؟", addSkill = "أضف مهارة", skillName = "اسم المهارة", makeQuest = "أنشئ المهمة",
            keepAtLeastOne = "أبقِ مهارة واحدة على الأقل.", slides = "شرائح",
            goingWell = "ممتاز", gettingThere = "يتقدّم", needsAnotherLook = "يحتاج مراجعة", notPlayedYet = "لم يبدأ بعد",
            firstTry = "صحيح من المحاولة الأولى", lastPractised = "آخر تدريب", queuedFor = "سيعود يوم", attempts = "إجابات",
            grade = "الصف", curriculum = "المنهج", save = "حفظ",
            practiceLength = "طول التدريب", questions = "أسئلة", language = "اللغة", changePin = "تغيير الرقم السري",
            deleteFiles = "حذف الملفات المرفوعة", deleteFilesBody = "يحذف كل ملفات الشرائح من الخادم. تبقى المهارات والأسئلة.",
            deleted = "تم حذف الملفات", privacy = "الخصوصية", privacyBody = "تُقرأ الشرائح مرة واحدة ثم تُحذف. تُحفظ المهارات والأسئلة فقط على هذا الجهاز.",
            version = "الإصدار", today = "اليوم", noLessonsThatDay = "لا يوجد درس في هذا اليوم.",
            statusLabel = mapOf("uploading" to "جارٍ الرفع", "reading" to "جارٍ القراءة", "needs_confirmation" to "بانتظار موافقتك", "generating" to "إعداد الأسئلة", "ready" to "جاهز", "error" to "مشكلة"),
            signIn = "تسجيل الدخول", register = "إنشاء حساب", signInBody = "الأهل يسجّلون الدخول؛ الأطفال يلعبون فقط.",
            email = "البريد الإلكتروني", password = "كلمة المرور", createAccount = "إنشاء حساب", googleSignIn = "المتابعة عبر Google",
            haveAccount = "لديّ حساب بالفعل", noAccount = "جديد هنا؟ أنشئ حسابًا",
            american = "أمريكي", british = "بريطاني",
            children = "الأطفال", signOut = "تسجيل الخروج",
            level = "المستوى", unlockLevel = "فتح", lessonPanel = "لوحة الدرس", objectives = "أهداف التعلّم",
            supported = "دعم", challengeIdeas = "تحدٍّ", tipsPerStop = "نصائح لكل خطوة", played = "مكتمل", notPlayed = "لم يبدأ بعد", playRecording = "تشغيل التسجيل",
            weakSkills = "يحتاج مراجعة", noWeakSkills = "لا شيء للمراجعة الآن — رائع!", streak = "أيام متتالية",

            examResultPending = "هذا اختبار. تظهر النتيجة والأسئلة وملاحظة المعلّمة هنا بعد أن تنشرها المعلّمة.",
            examUndeliveredTitle = "إجابات اختبار لم تُسلَّم",
            examUndeliveredBody = "{n} من إجابات «{title}» موجودة على هذا الجهاز فقط ولم تصل إلى المدرسة. افتح الاختبار مع اتصال بالإنترنت. إذا كان الاختبار قد أُغلق فاطلب من المعلّمة إعادة فتحه — الإجابات محفوظة وتُرسل عندها.",
            biometricFace = "بصمة الوجه", biometricTouch = "بصمة الإصبع", biometricGeneric = "البصمة",
            lockTitle = "{app} مقفل",
            lockBody = "افتح القفل باستخدام {with} أو رمز الجهاز.",
            lockBodyPasscode = "افتح القفل برمز الجهاز، أو سجّل الدخول بكلمة المرور.",
            lockReason = "فتح {app}",
            lockTryAgain = "حاول مرة أخرى",
            lockUsePassword = "تسجيل الدخول بكلمة المرور",
            biometricOfferTitle = "فتح القفل باستخدام {with}؟",
            biometricOfferBody = "في المرة القادمة، افتح {app} باستخدام {with} بدلاً من كلمة المرور. يمكنك تغيير ذلك من الإعدادات.",
            biometricOfferAccept = "تفعيل",
            biometricOfferDecline = "ليس الآن",
            security = "الأمان",
            biometricSetting = "فتح القفل باستخدام {with}",
            biometricSettingHint = "يُطلب عند فتح التطبيق، وبعد دقيقة من مغادرته، وعند دخول منطقة وليّ الأمر.",
            biometricOn = "مفعّل", biometricOff = "متوقف",
            parentAreaReason = "دخول منطقة وليّ الأمر",
            teacherMarks = "تقييم المعلّمة", teacherComment = "ملاحظة المعلّمة",
            teacherQuestionNote = "ملاحظة المعلّمة", needsAttention = "يحتاج انتباه", passed = "ناجح",
            scoreBands = mapOf("emerging" to "مبتدئ", "developing" to "في تطوّر", "secure" to "متمكّن", "exceeding" to "متفوّق"),
            accuracyWords = mapOf("almost every time" to "في كل مرة تقريبًا", "most of the time" to "في معظم الأحيان", "more than half the time" to "أكثر من نصف المرات", "some of the time" to "أحيانًا", "not yet" to "ليس بعد"),
            weekdays = listOf("ن", "ث", "ر", "خ", "ج", "س", "ح"),
            months = listOf("يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"),
            messages = "الرسائل",
            chat = "المحادثة",
            noTeachers = "لم يتم تعيين معلمين بعد",
            childNotPlaced = "لم يتم تسكين طفلك في فصل بعد. يرجى التواصل مع المدرسة لتسكينه.",
            typeMessage = "اكتب رسالة…",
            send = "إرسال",
            online = "متصل",
            offline = "غير متصل",
            connecting = "جارٍ الاتصال…",
            isTyping = "يكتب الآن…",
            emptyConversation = "لا توجد رسائل بعد. أرسل ملاحظة للمعلمة!",
            retry = "إعادة المحاولة",
            failedToSend = "فشل الإرسال",
            chatDisabled = "المحادثة معطّلة حالياً من قبل المدرسة.",
            attendance = "الحضور والغياب",
            todaysAttendance = "حضور اليوم",
            present = "حاضر",
            absent = "غائب",
            late = "متأخر",
            excused = "معذور",
            noAttendanceRecorded = "لم يُسجل بعد",
            attendanceNote = "ملاحظة المعلم",
            teacherRole = "معلّمة",
            coordinatorRole = "منسّق المادة",
            teachersGroup = "معلّمو طفلك",
            coordinatorsGroup = "منسّقو المواد",
            pickCoordinator = "إلى مَن تريد أن تكتب؟",
            complaintBadge = "شكوى",
            statusOpen = "مفتوحة",
            statusResolved = "تم الحل",
            resolvedBanner = "تم الحل — ردّ المنسّق على هذه الرسالة. لا يزال بإمكانك الكتابة هنا.",
            resolvedBannerTeacher = "تم الحل — ردّت المعلّمة على هذه الرسالة. لا يزال بإمكانك الكتابة هنا.",
            resolvedBannerManager = "تم الحل — ردّ مدير القسم على هذه الرسالة. لا يزال بإمكانك الكتابة هنا.",
            resolvedBannerAdmin = "تم الحل — ردّت إدارة المدرسة على هذه الرسالة. لا يزال بإمكانك الكتابة هنا.",
            markAsComplaint = "هذه شكوى",
            markAsComplaintHint = "ستظهر كشكوى مفتوحة في قائمة الشكاوى عند المنسّق.",
            subjectNames = mapOf(
                "math" to "رياضيات", "english" to "إنجليزي", "science" to "علوم",
                "french" to "فرنسي", "religion" to "تربية إسلامية", "arabic" to "عربي",
            ),
            emptyConversationCoordinator = "لا توجد رسائل بعد. اكتب إلى منسّق هذه المادة.",
            managerRole = "مدير القسم",
            managersGroup = "مدير القسم",
            emptyConversationManager = "لا توجد رسائل بعد. اكتب إلى مدير القسم.",
            markAsComplaintHintManager = "ستظهر كشكوى مفتوحة في قائمة الشكاوى عند مدير القسم.",
            weeklyPlan = "الخطة الأسبوعية",
            announcements = "الإعلانات",
            notificationsTitle = "الإشعارات",
            updatesGroup = "المستجدات",
            updateMessage = "رسالة",
            updateResult = "صدرت النتيجة",
            updateHomework = "واجب جديد",
            updateOther = "تحديث",
            notices = NoticeStrings.ar,
            thisWeeksPlan = "خطة هذا الأسبوع",
            earlierPlans = "أسابيع سابقة",
            weekOf = "أسبوع {date}",
            announcementsGroup = "إعلانات",
            eventsGroup = "فعاليات",
            noBroadcasts = "لا يوجد جديد من المدرسة بعد.",
            noWeeklyPlan = "لا توجد خطة أسبوعية بعد. يرسل مدير القسم خطة كل أسبوع.",
            imageFailed = "لم يتم تنزيل الخطة. حاول مرة أخرى عند توفر الإنترنت.",
            tapToClose = "اضغط للإغلاق",
            broadcastsDisabled = "هذه الميزة غير مفعّلة في مدرستك.",
            newBadge = "جديد",
            attachment = "مرفق",
            attachmentOnDashboard = "متاح في لوحة التحكم",
            phone = "رقم الجوال",
            phoneHint = "لتتمكن المدرسة من التواصل معك، مثال: ‎+971501234567",
            phoneInvalid = "رقم الجوال من 7 إلى 15 رقمًا، ويمكن أن يبدأ بعلامة +.",
            phoneSaved = "تم الحفظ",
            phoneSaveFailed = "تعذّر الحفظ الآن. تحقق من الاتصال وحاول مرة أخرى.",
            fromCoordinator = "من منسّق {subject}",
            fromManager = "من مدير قسم {curriculum}",
            fromAuthor = "من {name}",
            allSubjects = "كل المواد",
            student = "الطالب",
            dayStreakShort = "{n} يوم متتابع",
            loadingCoursework = "جارٍ تحميل دروسك…",
            noCourseworkToday = "لا توجد دروس مجدولة اليوم",
            noCourseworkForSubject = "لا توجد دروس في هذه المادة",
            checkBackSoon = "عُد قريباً لدروس ومهام جديدة.",
            lessonLocked = "مقفل",
            lessonCompleted = "مكتمل",
            lessonReview = "مراجعة",
            lessonAssignedToday = "درس اليوم",
            lessonAvailable = "متاح",
            lessonUnlockHint = "أكمل الدروس السابقة لفتحه",
            lessonReinforce = "ترسيخ المفاهيم",
            lessonStandard = "درس من المنهج",
            startLesson = "ابدأ الدرس",
            openLesson = "افتح",
            parentPortal = "بوابة ولي الأمر",
            lessonScore = "النتيجة: {earned}/{total}",
            pdfDocument = "مستند PDF",
            openDocument = "فتح",
            documentOpening = "جارٍ الفتح…",
            documentFailed = "تعذّر فتح الملف. تحقق من الاتصال ومن وجود تطبيق لعرض ملفات PDF على هذا الجهاز.",
            appName = "مدرستي",
            appearance = "المظهر",
            appearanceSystem = "حسب النظام",
            appearanceLight = "فاتح",
            appearanceDark = "داكن",
            schoolAdministration = "إدارة المدرسة",
            emptyConversationAdmin = "لا توجد رسائل بعد.",
            newMessage = "رسالة جديدة",
            newMessageChild = "عن أيّ طفل؟",
            newMessageTopic = "ما نوع الرسالة؟",
            topicQuestion = "سؤال",
            topicComplaint = "شكوى",
            complaintExplained = "تظهر الشكوى بشارة وحالة — مفتوحة ثم تم الحل — لك ولمن تُرسلها إليه.",
            newMessageNobody = "لا يوجد من تراسله لهذا الطفل بعد.",
            markAsComplaintHintTeacher = "ستراها المعلّمة كشكوى مفتوحة.",
            chooseStudent = "اختر طالباً لفتح صفحته الرئيسية.",
            currentChild = "الحالي",
            noChildrenLinked = "لم تربط مدرستك أي طفل بهذا الحساب بعد — يرجى التواصل مع المدرسة.",
            checkAgain = "تحقّق مرة أخرى",
            lesson = LessonStrings.ar,
        )

        fun forLanguage(code: String) = if (code == "ar") ar else en
    }
}

val LocalStrings = staticCompositionLocalOf { Strings.en }

/**
 * The name the app shows for itself: the school's or the platform's when either has one, otherwise the product's own
 * name in the reader's language — MySchool, مدرستي.
 */
fun SchoolBranding.displayName(strings: Strings): String = if (appName == SchoolBranding.DEFAULT_APP_NAME) strings.appName else appName

/** M5: the newer kinds a parent is told about, and what a tapped notification opens on the Notifications tab. */
data class NoticeStrings(
    val updateExam: String,
    val updateClassNote: String,
    val updateQuestion: String,
    val updateComplaint: String,
    val updateNews: String,
    val fromYourNotification: String,
    val itemGone: String,
) {
    companion object {
        val en = NoticeStrings(
            updateExam = "New exam", updateClassNote = "Class note", updateQuestion = "Teacher question",
            updateComplaint = "Complaint update", updateNews = "School news",
            fromYourNotification = "From your notification", itemGone = "That item is no longer available.",
        )
        val ar = NoticeStrings(
            updateExam = "اختبار جديد", updateClassNote = "ملاحظة للصف", updateQuestion = "سؤال من المعلّم",
            updateComplaint = "تحديث على الشكوى", updateNews = "أخبار المدرسة",
            fromYourNotification = "من الإشعار", itemGone = "هذا العنصر لم يعد متاحاً.",
        )
    }
}
