#!/usr/bin/env node
/**
 * Generates the typed API client from the server's contract.
 *
 *   node tools/gen-api.mjs            generate into src/app/api/generated
 *   node tools/gen-api.mjs --check    fail when the contract cannot be generated
 *
 * `server/openapi.json` is written by the backend's `OpenApiExportTest` and is the only
 * description of the API this workspace is allowed to know about: every call the dashboard
 * makes goes through a service generated here (`hq/no-raw-http` fails the build on an
 * `HttpClient` injected anywhere else). The output is git-ignored and regenerated by
 * `postinstall`, so the contract can never drift from the checked-in client — there is no
 * checked-in client.
 *
 * openapi-generator is a Java program. Every environment that installs this workspace must
 * therefore have a JRE on PATH: GitHub's `ubuntu-latest` image ships Temurin, and the Docker
 * build stage needs one added (see the P3.1 report). When Java is missing this script fails
 * loudly rather than leaving an empty folder behind — a silent no-op would surface as a
 * hundred "cannot find module" errors in `ng build` instead.
 */
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const SPEC = resolve(root, '../server/openapi.json');
const OUT = resolve(root, 'src/app/api/generated');

/** Kept in step with `@angular/core` in package.json; the generator branches on it. */
const NG_VERSION = '22.1.0';

const properties = [
  `ngVersion=${NG_VERSION}`,
  'fileNaming=kebab-case',
  'serviceSuffix=Api',
  'serviceFileSuffix=.api',
  'modelFileSuffix=',
  'providedInRoot=true',
  'withInterfaces=true',
  'useSingleRequestParameter=false',
  'stringEnums=true',
  'supportsES6=true',
  'enumPropertyNaming=UPPERCASE',
  'taggedUnions=false',
  'legacyDiscriminatorBehavior=false',
].join(',');

function fail(message) {
  process.stderr.write(`gen:api — ${message}\n`);
  process.exit(1);
}

if (!existsSync(SPEC)) fail(`${SPEC} does not exist. The backend publishes it from OpenApiExportTest.`);

const java = spawnSync('java', ['-version'], { stdio: 'ignore' });
if (java.error || java.status !== 0)
  fail(
    'no `java` on PATH. openapi-generator is a Java program; install a JRE (17 or newer) ' +
      'or add actions/setup-java to the job running this install.',
  );

rmSync(OUT, { recursive: true, force: true });

const generator = resolve(root, 'node_modules/.bin/openapi-generator-cli');
const result = spawnSync(
  generator,
  [
    'generate',
    '--input-spec',
    SPEC,
    '--generator-name',
    'typescript-angular',
    '--output',
    OUT,
    '--additional-properties',
    properties,
    '--skip-validate-spec',
    '--global-property',
    'apiDocs=false,modelDocs=false,apiTests=false,modelTests=false',
  ],
  { cwd: root, stdio: ['ignore', 'pipe', 'pipe'], encoding: 'utf8' },
);

if (result.status !== 0) {
  process.stderr.write(result.stdout ?? '');
  process.stderr.write(result.stderr ?? '');
  fail(`openapi-generator exited with ${result.status ?? 'a signal'}.`);
}

// The generator writes a library scaffold (package.json, tsconfig, .openapi-generator-ignore,
// README, git_push.sh) next to the client. None of it belongs in an application source folder,
// and `tsconfig.app.json` would try to compile the stray `index.ts` of a second project.
for (const stray of [
  'package.json',
  'tsconfig.json',
  'ng-package.json',
  'README.md',
  'git_push.sh',
  '.gitignore',
])
  rmSync(resolve(OUT, stray), { force: true });

// `api.module.ts` is the NgModule era: a module that declares every service as a provider, plus
// an `APIS` array in `api/api.ts` that *names* all fourteen of them. Both are dead weight in a
// standalone app — and worse than dead, because that array is a static reference from the
// barrel to every service, which pins all fourteen into whichever chunk first imports the
// barrel. Deleting them is what lets a route that talks to two endpoints ship two services.
rmSync(resolve(OUT, 'api.module.ts'), { force: true });
rewrite(resolve(OUT, 'api/api.ts'), (source) =>
  source
    .split('\n')
    .filter((line) => line.startsWith('export * from'))
    .join('\n')
    .concat('\n'),
);
rewrite(resolve(OUT, 'index.ts'), (source) =>
  source
    .split('\n')
    .filter((line) => !line.includes('./api.module'))
    .join('\n'),
);

const count = countFiles(OUT);
process.stdout.write(`gen:api — ${count} files in src/app/api/generated (${NG_VERSION})\n`);
if (count === 0) fail('the generator produced nothing.');

function rewrite(path, transform) {
  writeFileSync(path, transform(readFileSync(path, 'utf8')));
}

function countFiles(dir) {
  let total = 0;
  for (const entry of readdirSync(dir)) {
    const path = resolve(dir, entry);
    total += statSync(path).isDirectory() ? countFiles(path) : 1;
  }
  return total;
}
