#!/usr/bin/env node
/**
 * Compiles `shared-api`'s `Play.schema.json` into **standalone** validators the stop editor can
 * run in the browser.
 *
 *   node tools/schemas.mjs           write src/app/features/lessons/stop-validators.generated.js
 *   node tools/schemas.mjs --check   fail (exit 1) when the output would differ from what is there
 *
 * **Why precompiled and not Ajv at runtime.** Ajv builds a validator by `new Function(...)`, and
 * the server sends `Content-Security-Policy: default-src 'self'` with no `'unsafe-eval'` — so an
 * in-browser `ajv.compile()` throws `EvalError` on the real thing while passing every test in
 * jsdom. Ajv's standalone mode emits the same validator as plain JavaScript at build time: no
 * eval, no CSP exception to argue for, and ~130 kB of Ajv that never reaches a browser at all.
 *
 * One validator per `$defs.stop_<type>` branch, not one for the whole `oneOf`: the editor
 * validates a stop against the type it declares, so the errors name that type's missing field
 * instead of twenty-two branches' worth at once (see `stop-validator.ts`).
 *
 * The output is generated, not committed — `gen:api`'s rule, for the same reason: it is derived
 * from a file in this repository, and `postinstall` runs both.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const Ajv2020 = require('ajv/dist/2020');
const standaloneCode = require('ajv/dist/standalone').default;

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = resolve(here, '../../shared-api/src/commonMain/resources/schemas/Play.schema.json');
const TARGET = resolve(here, '../src/app/features/lessons/stop-validators.generated.js');
const TYPES = resolve(here, '../src/app/features/lessons/stop-validators.generated.d.ts');

const BANNER = `// Generated by \`pnpm schemas\` from shared-api/.../Play.schema.json — do not edit.
// Ajv standalone output: no \`new Function\`, so it runs under the server's CSP.
`;

const DECLARATION = `// Generated by \`pnpm schemas\` — do not edit.
export interface StopSchemaError {
  readonly instancePath: string;
  readonly message?: string;
  readonly params?: { readonly additionalProperty?: string };
}
export interface StopSchemaValidator {
  (data: unknown): boolean;
  errors?: readonly StopSchemaError[] | null;
}
/** One compiled validator per \`Play.schema.json\` \`$defs.stop_<type>\` branch, keyed by \`type\`. */
export declare const STOP_VALIDATORS: Readonly<Record<string, StopSchemaValidator>>;
`;

/** `$defs.stop_readPage` → the `type` const it declares (`readPage`). */
export function stopTypesOf(schema) {
  return Object.entries(schema.$defs ?? {})
    .filter(([name]) => name.startsWith('stop_'))
    .map(([name, def]) => ({ name, type: def?.properties?.type?.const }))
    .filter((entry) => typeof entry.type === 'string');
}

function render(schema) {
  const branches = stopTypesOf(schema);
  const ajv = new Ajv2020({ allErrors: true, strict: false, code: { source: true, esm: true } });
  ajv.addSchema(schema, 'play');

  const byExportName = Object.fromEntries(branches.map((b) => [exportNameOf(b.type), `play#/$defs/${b.name}`]));
  const code = standaloneCode(ajv, byExportName);

  const map = branches.map((b) => `  ${JSON.stringify(b.type)}: ${exportNameOf(b.type)},`).join('\n');
  return `${BANNER}${code}\nexport const STOP_VALIDATORS = Object.freeze({\n${map}\n});\n`;
}

/** Ajv names each export after this key, so it has to be a plain JavaScript identifier. */
function exportNameOf(type) {
  return `validate_${type}`;
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  const schema = JSON.parse(readFileSync(SOURCE, 'utf8'));
  const next = render(schema);
  const count = stopTypesOf(schema).length;

  if (process.argv.includes('--check')) {
    let current;
    try {
      current = readFileSync(TARGET, 'utf8');
    } catch {
      current = ''; // never generated here — same answer as "generated and stale"
    }
    if (current !== next) {
      process.stderr.write('schemas — stop-validators.generated.js is stale. Run `pnpm schemas`.\n');
      process.exit(1);
    }
    process.stdout.write(`schemas — up to date (${count} stop validators)\n`);
  } else {
    writeFileSync(TARGET, next);
    writeFileSync(TYPES, DECLARATION);
    process.stdout.write(`schemas — ${count} stop validators\n`);
  }
}
