package quest.feature.complaints.presentation

/** M8: the Complaints page's copy in English and Arabic — `Strings.complaints`. `{name}` and `{date}` are filled in. */
data class ComplaintStrings(
    val title: String,
    val newComplaint: String,
    val filterOpen: String,
    val filterResolved: String,
    val filterAll: String,
    val statusOpen: String,
    val statusResolved: String,
    val empty: String,
    val emptyOpen: String,
    val emptyResolved: String,
    val aboutChild: String,
    val toWhom: String,
    val nobody: String,
    val titleLabel: String,
    val titleHint: String,
    val messageLabel: String,
    val messageHint: String,
    val send: String,
    val explained: String,
    val to: String,
    val reply: String,
    val reopen: String,
    val resolvedNote: String,
    val readOnly: String,
    val resolvedBy: String,
    val reopenedBy: String,
    val you: String,
    /** Before her own last message in a list row. */
    val youSaid: String,
    val unread: String,
    val movedNotice: String,
    val openComplaints: String,
    val sendFailed: String,
    /** The accessible label of a failed reply's Retry. */
    val retryReply: String,
    val reopenFailed: String,
) {
    companion object {
        val en = ComplaintStrings(
            title = "Complaints",
            newComplaint = "New complaint",
            filterOpen = "Open",
            filterResolved = "Resolved",
            filterAll = "All",
            statusOpen = "Open",
            statusResolved = "Resolved",
            empty = "No complaints. If something is not right, tell a teacher, a subject coordinator or the department manager here.",
            emptyOpen = "No open complaints.",
            emptyResolved = "No resolved complaints yet.",
            aboutChild = "About which child?",
            toWhom = "Who is it for?",
            nobody = "There is nobody to send a complaint to for this child yet.",
            titleLabel = "Title",
            titleHint = "In a few words, what is it about?",
            messageLabel = "Your message",
            messageHint = "Tell them what happened",
            send = "Send complaint",
            explained = "Only you and the person you choose write in a complaint. They mark it resolved; you can reopen it.",
            to = "To {name}",
            reply = "Write a reply",
            reopen = "Reopen complaint",
            resolvedNote = "This complaint is resolved. You can still reply, or reopen it if it is not settled.",
            readOnly = "You can read this complaint.",
            resolvedBy = "Resolved by {name} · {date}",
            reopenedBy = "Reopened by {name} · {date}",
            you = "you",
            youSaid = "You: ",
            unread = "unread",
            movedNotice = "Complaints have their own page now. Write your complaint there.",
            openComplaints = "Go to Complaints",
            sendFailed = "The complaint was not sent. Check the connection and try again.",
            retryReply = "Send this reply again",
            reopenFailed = "The complaint was not reopened. Check the connection and try again.",
        )

        val ar = ComplaintStrings(
            title = "الشكاوى",
            newComplaint = "شكوى جديدة",
            filterOpen = "مفتوحة",
            filterResolved = "تم الحل",
            filterAll = "الكل",
            statusOpen = "مفتوحة",
            statusResolved = "تم الحل",
            empty = "لا توجد شكاوى. إن كان هناك ما يزعجك، أخبر المعلّمة أو منسّق المادة أو مدير القسم من هنا.",
            emptyOpen = "لا توجد شكاوى مفتوحة.",
            emptyResolved = "لا توجد شكاوى تم حلّها بعد.",
            aboutChild = "عن أيّ طفل؟",
            toWhom = "إلى مَن؟",
            nobody = "لا يوجد بعد من تُرسل إليه شكوى بخصوص هذا الطفل.",
            titleLabel = "العنوان",
            titleHint = "بكلمات قليلة، عمّ تدور الشكوى؟",
            messageLabel = "رسالتك",
            messageHint = "اشرح ما حدث",
            send = "إرسال الشكوى",
            explained = "لا يكتب في الشكوى إلا أنت ومن تختاره. هو يحدّدها بأنها تم حلّها، ويمكنك إعادة فتحها.",
            to = "إلى {name}",
            reply = "اكتب ردًّا",
            reopen = "إعادة فتح الشكوى",
            resolvedNote = "تم حل هذه الشكوى. لا يزال بإمكانك الرد، أو إعادة فتحها إن لم تُحسم.",
            readOnly = "يمكنك قراءة هذه الشكوى.",
            resolvedBy = "تم الحل بواسطة {name} · {date}",
            reopenedBy = "أُعيد فتحها بواسطة {name} · {date}",
            you = "أنت",
            youSaid = "أنت: ",
            unread = "غير مقروءة",
            movedNotice = "أصبح للشكاوى صفحة خاصة بها. اكتب شكواك هناك.",
            openComplaints = "الانتقال إلى الشكاوى",
            sendFailed = "لم تُرسل الشكوى. تحقّق من الاتصال وحاول مجددًا.",
            retryReply = "أعد إرسال هذا الرد",
            reopenFailed = "لم يُعد فتح الشكوى. تحقّق من الاتصال وحاول مجددًا.",
        )
    }
}
