/**
 * Generated by `pnpm gen:permissions` from server/src/main/resources/permissions.json.
 * Do not edit: `permissions.generated.spec.ts` re-derives it and fails on drift.
 *
 * A permission is a **write** when at least one endpoint declaring it uses a method other than
 * GET or HEAD — which is exactly what a read-only "View as" session is refused.
 */
export const WRITE_PERMISSIONS: ReadonlySet<string> = new Set([
  'auth.changePassword',
  'auth.forgotPassword',
  'auth.refresh',
  'auth.resetPassword',
  'auth.signIn',
  'auth.signOut',
  'child.play',
  'child.write',
  'class.write',
  'flag.write',
  'invite.accept',
  'lesson.delete',
  'lesson.publish',
  'lesson.write',
  'platform.write',
  'play.write',
  'school.write',
  'stop.write',
  'theme.write',
  'user.create',
  'user.impersonate',
  'user.invite',
  'user.write',
]);
