/**
 * Generated by `pnpm gen:permissions` from server/src/main/resources/permissions.json.
 * Do not edit: `permissions.generated.spec.ts` re-derives it and fails on drift.
 *
 * A permission is a **write** when at least one endpoint declaring it uses a method other than
 * GET or HEAD — which is exactly what a read-only "View as" session is refused.
 */
export const WRITE_PERMISSIONS: ReadonlySet<string> = new Set([
  'announcement.write',
  'auth.changePassword',
  'auth.forgotPassword',
  'auth.refresh',
  'auth.resetPassword',
  'auth.signIn',
  'auth.signOut',
  'child.play',
  'child.teacherQuestion.answer',
  'child.write',
  'class.lookup',
  'class.write',
  'flag.write',
  'invite.accept',
  'lesson.delete',
  'lesson.publish',
  'lesson.write',
  'me.update',
  'platform.write',
  'play.write',
  'question.send',
  'question.write',
  'roster.teacher',
  'roster.write',
  'school.logo',
  'school.write',
  'stop.write',
  'teacher.lesson.copy',
  'teacher.lesson.publish',
  'teacher.manage',
  'teacher.profile',
  'teacher.profile.manage',
  'theme.write',
  'user.create',
  'user.impersonate',
  'user.invite',
  'user.write',
]);
